version: '3'

services:
  mysite:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mydsite
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL && python3 manage.py runserver 0.0.0.0:8089"
    restart: always
    volumes:
      - .:/app
    expose:
      - "8089"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgre$
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  kong:
    image: kong_nodb
    container_name: kong_nodb
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: kong.yml
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8000"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"