version: '3'
services:
  mysite:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mydsite
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgre$
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
