# Generated by Django 4.2.10 on 2024-03-03 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_post_author_remove_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='unique_name_email',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='polls.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
